x = []
y = []
ax = int(input('Введите x первой точки '))
x.append(ax)
ay = int(input('Введите y первой точки '))
y.append(ay)
bx = int(input('Введите x второй точки '))
x.append(bx)
by = int(input('Введите y второй точки '))
y.append(by)
cx = int(input('Введите x третьей точки '))
x.append(cx)
cy = int(input('Введите y третьей точки '))
y.append(cy)
dx = int(input('Введите x четвёртой точки '))
x.append(dx)
dy = int(input('Введите y четвёртой точки '))
y.append(dy)
xmax = max(x)
ymax = max(y)
xmin = min(x)
ymin = min(y)
print('искомый прямоугольник задаётся следующими сторонами: x = ',xmax,', x = ',xmin,', y = ',ymax,', y = ',ymin)
